[package]
name = "opinion-trade-api"
version = "0.1.0"
edition = "2024"
rust-version = "1.91.0"
description = "API client for https://opinion.trade/"
homepage = "https://github.com/DenisGorbachev/opinion-trade-api"
repository = "https://github.com/DenisGorbachev/opinion-trade-api"
readme = "README.md"
keywords = []
categories = []
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.json",
    "commitlint.config.mjs",
    "lefthook.yml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    ".yolobox"
]

[package.metadata.details]
title = ""
tagline = ""
summary = ""
announcement = ""
readme = { generate = false }

[dependencies]
derive-new = "0.7.0"
derive_more = { version = "2.1.1", features = ["full"] }
strum = { version = "0.27.2", features = ["derive"] }
futures = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
rkyv = { version = "0.8.16", optional = true }
bon = { version = "3.9.0", features = ["implied-bounds"] }
thiserror = "2.0.18"

[dev-dependencies]
errgonomic = { git = "https://github.com/DenisGorbachev/errgonomic" }
tokio = { version = "1.49.0", features = ["macros", "fs", "net", "rt", "rt-multi-thread"] }
clap = { version = "4.5.60", features = ["derive", "env"] }
